version: '3.1'

services:
    flowise:
        build:
            context: ..
            dockerfile: Dockerfile
        restart: always
        environment:
            - PORT=${PORT}
            - CORS_ORIGINS=${CORS_ORIGINS}
            - IFRAME_ORIGINS=${IFRAME_ORIGINS}
            - FLOWISE_USERNAME=${FLOWISE_USERNAME}
            - FLOWISE_PASSWORD=${FLOWISE_PASSWORD}
            - FLOWISE_FILE_SIZE_LIMIT=${FLOWISE_FILE_SIZE_LIMIT}
            - DEBUG=${DEBUG}
            - DATABASE_PATH=${DATABASE_PATH}
            - DATABASE_TYPE=postgres
            - DATABASE_PORT=${DATABASE_PORT:-5432}
            - DATABASE_HOST=postgres
            - DATABASE_NAME=${DATABASE_NAME:-flowise}
            - DATABASE_USER=${DATABASE_USER:-flowiseuser}
            - DATABASE_PASSWORD=${DATABASE_PASSWORD:-flowisepassword}
            - DATABASE_SSL=${DATABASE_SSL}
            - DATABASE_SSL_KEY_BASE64=${DATABASE_SSL_KEY_BASE64}
            - APIKEY_PATH=${APIKEY_PATH}
            - SECRETKEY_PATH=${SECRETKEY_PATH}
            - FLOWISE_SECRETKEY_OVERWRITE=${FLOWISE_SECRETKEY_OVERWRITE}
            - LOG_LEVEL=${LOG_LEVEL}
            - LOG_PATH=${LOG_PATH}
            - BLOB_STORAGE_PATH=${BLOB_STORAGE_PATH}
            - DISABLE_FLOWISE_TELEMETRY=${DISABLE_FLOWISE_TELEMETRY}
            - MODEL_LIST_CONFIG_JSON=${MODEL_LIST_CONFIG_JSON}
        ports:
            - '127.0.0.1:${PORT}:${PORT}'
        volumes:
            - ~/.flowise:/root/.flowise
        entrypoint: /bin/sh -c "sleep 3; pnpm start"
        depends_on:
            - postgres

    postgres:
        image: postgres:13
        restart: always
        environment:
            POSTGRES_DB: ${DATABASE_NAME:-flowise}
            POSTGRES_USER: ${DATABASE_USER:-flowiseuser}
            POSTGRES_PASSWORD: ${DATABASE_PASSWORD:-flowisepassword}
        volumes:
            - postgres_data:/var/lib/postgresql/data

volumes:
    postgres_data:
